web/notifications/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import HiddenField
from wtforms.validators import InputRequired


class FollowForm(FlaskForm):
    id=HiddenField(
        'id',
        validators=[InputRequired()]
    )
    action=HiddenField(
        'action',
        validators=[InputRequired()]
    )
    type=HiddenField(
        'type',
        default='follow',
        validators=[InputRequired()]
    )


class TagForm(FlaskForm):
    id=HiddenField(
        'id',
        validators=[InputRequired()]
    )
    action=HiddenField(
        'action',
        validators=[InputRequired()]
    )
    type=HiddenField(
        'type',
        default='tag',
        validators=[InputRequired()]
    )

web/notifications/__init__.py
from .notifications import enable_notifications
from .forms import TagForm, FollowForm

web/photos/__init__.py
from .routes import photos

web/photos/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from ..app import db

photos=Blueprint('photos', __name__, url_prefix='/p')


@photos.route('/<photoID>')
@login_required
def view(photoID):
    p=db.query('Photo').find(
        photoID=photoID,
    ).first()

    if p is None:
        return redirect(url_for('home.index'))

    follows=db.query('Follow').find(
        followerUsername=current_user.username,
        followeeUsername=p.PhotoOwner
    ).first()

    if follows is None or not follows.acceptedfollow or not p.allFollowers:
        return redirect(url_for('home.index'))

    shares = list(p.shares)

    if len(shares) != 0:
        share=shares[0]
        if all(
            share.groupName != group.groupName and share.groupOwner != group.groupName
            for group in current_user.closefriendgroups
        ):
            return redirect('home.index')

    return render_template(
        'photos/view.html',
        photo=p
    )

web/users/routes.py
from functools import wraps

import pymysql.cursors
from flask import render_template, Blueprint, redirect, request, flash
from flask_login import current_user, login_required

from bigsql import bigsql
from .forms import FollowForm, SearchForm
from .. import home
from .. import models
from ..app import db
from ..notifications import enable_notifications

users=Blueprint('users', __name__, url_prefix='/u')


def validate(func):
    """
    validates forms before executing func
    """

    @wraps(func)
    def wrapper(form):
        if form.validate_on_submit():
            return func(form)

    return wrapper


@validate
def handle_follow(form):
    db.query('Follow').new(
        followerUsername=current_user.username,
        followeeUsername=form.id.data,
        acceptedfollow=False
    )
    try:
        db.session.commit()
    except bigsql.big_ERROR:
        db.session.rollback()


@validate
def handle_unfollow(form):
    f=db.query('Follow').find(
        followerUsername=current_user.username,
        followeeUsername=form.id.data,
        acceptedfollow=True
    ).first()
    if f is not None:
        db.session.delete(f)
        try:
            db.session.commit()
        except bigsql.big_ERROR:
            db.session.rollback()
    else:
        flash('unable to unfollow')


@validate
def search_users(form):
    return db.query('Person').append_raw(
        'WHERE Person.username LIKE %s',
        ('%%{}%%'.format(form.content.data),)
    ).all()


def handle_users(func):
    @wraps(func)
    def handler(*args, **kwargs):
        follow_form=FollowForm()
        if request.method == 'POST':
            try:
                {
                    'follow'  : lambda: handle_follow(follow_form),
                    'unfollow': lambda: handle_unfollow(follow_form),
                    None      : lambda: None
                }[request.form.get('action', default=None)]()
            except KeyError:
                pass
            except pymysql.err.IntegrityError:
                db.session.rollback()
        return func(*args, **kwargs)

    return handler


@users.route('/', methods=['GET', 'POST'])
@login_required
@enable_notifications
@home.handle_photos
@handle_users
def index():
    search_form=SearchForm()

    persons=None

    if request.form.get('action', default=None) == 'search':
        persons=search_users(search_form)

    return render_template(
        'users/home.html',
        FollowForm=FollowForm,
        search_form=search_form,
        persons=persons if persons is not None else models.Person.query.all()
    )


@users.route('/<username>', methods=['GET', 'POST'])
@login_required
@enable_notifications
@home.handle_photos
@handle_users
def view(username):
    person=db.query('Person').find(
        username=username
    ).first()

    if person is None:
        return redirect('home.index')

    return render_template(
        'users/view.html',
        person=person,
        photos=db.sql.SELECTFROM('Photo').WHERE(
            photoOwner=person.username
        ).AND(
            allFollowers=True
        ).all()
    )

web/templates/base.html
{% from 'bootstrap/form.html' import render_form, render_field %}
{% from 'bootstrap/nav.html' import render_nav_item %}
{% from "photo.html" import render_photo, render_photos %}
{% from "form.html" import make_form %}
{% from "notifications.html" import render_notifications with context %}

{% macro nav_item(endpoint, name) %}
  <button type="button" class="btn btn-outline-success ml-2">
    {{ render_nav_item(endpoint, name, use_li=True) }}
  </button>
{% endmacro %}

<!DOCTYPE html>
<html lang="en">
{% block header %}
  <head>
    {% block title %}
      <title>tandon.singles</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{ bootstrap.load_css() }}
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block stylesheets %}{% endblock %}
  </head>
{% endblock %}

<body>
<nav class="navbar navbar-expand-sm navbar-inverse" id="top-navbar">
  <div class="container-fluid h-100">
    {% block navbarleft %}
      <ul class="nav navbar-nav navbar-expand-sm">
        <li class="nav-item">
          <button type="button" class="btn btn-outline-primary pl-3 pr-0">
            <a class="navbar-brand" href="{{ url_for('home.index') }}" id="index-nav">tandon.singles</a>
          </button>
        </li>
        {{ nav_item('groups.manage', 'groups') }}
        {{ nav_item('users.index', 'users') }}
      </ul>
    {% endblock navbarleft %}

    {% block navbarright %}
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <button type="button" class="btn btn-outline-success m-2">
              <a href="{{ url_for('users.view', username=current_user.username) }}" class="nav-link">
                {{ current_user.username }}
              </a>
            </button>
          </li>
          <li id="logout-nav">
            <a href="{{ url_for('auth.logout') }}" class="nav-link align-self-center">
              <button type="button" class="btn btn-outline-warning m-2">
                <div class="d-flex flex-row">
                  Logout
                  <i class="fas fa-sign-out-alt align-self-center p-1"></i>
                </div>
              </button>
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{{ url_for('auth.login') }}" class="nav-link align-self-center">
              <button type="button" class="btn btn-outline-warning m-2">
                <div class="d-flex flex-row">
                  Login
                  <i class="fas fa-sign-in-alt align-self-center p-1"></i>
                </div>
              </button>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endblock %}
  </div>
</nav>
<br>

<main role="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        {%- with messages = get_flashed_messages() %}
          {%- if messages %}
            {% for message in messages %}
              <div class="alert alert-danger alert-dismissable" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
            {% endfor %}
          {%- endif %}
        {%- endwith %}
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</main>

{% block scripts %}
  {{ bootstrap.load_js() }}
  <script src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}
</body>
</html>

web/templates/form.html
{% from 'bootstrap/form.html' import render_form %}

{% macro make_form(form, form_title='', include_flash=False) %}
  <div class="container pb-4 pt-4">
    <div class="row">
      <div class="col-sm-4 offset-sm-4">
        <div class="jumbotron mx-auto">
          <h1>{{ form_title }}</h1>
          {% if include_flash %}
            {%- with messages = get_flashed_messages() %}
              {%- if messages %}
                <div class="alert alert-danger" role="alert">
                  {% for message in messages %}
                    {{ message }}
                  {% endfor %}
                </div>
              {%- endif %}
            {%- endwith %}
          {% endif %}
          {{ render_form(form) }}
          <br>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

web/templates/notifications.html
{% macro render_notification(obj) %}
  <div class="card notification mt-3">
    <div class="card-body">
      {% set form = obj.to_form() %}

      {{ form.id }}
      {{ form.type }}

      <p class="card-text">
        {% if form.type.data == "follow" %}
          Accept follow from
          <a href="{{ url_for('users.view', username=form.id.data) }}">{{ form.id.data }}</a>
        {% elif form.type.data == "tag" %}
          {% set username = obj.photo.photoOwner %}
          Accept
          <a href="{{ url_for('photos.view', photoID=form.id.data) }}">
            tag
          </a>
          from
          <a href="{{ url_for('users.view', username=username) }}">
            {{ username }}
          </a>
        {% endif %}
      </p>

      <button type="button" class="btn btn-outline-success accept-not">
        Accept
      </button>
      <button type="button" class="btn btn-outline-danger reject-not">
        Reject
      </button>
    </div>
  </div>
{% endmacro %}

{% macro render_notifications() %}
  <div class="col-md-2 offset-md-1">
    <div class="rounded pl-1 pr-1">
      <ul class="nav flex-column">
        {% set objs = current_user.notifications %}
        {% for n in objs %}
          <li class="nav-item">
            {{ render_notification(n) }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="col-md-1"></div>
{% endmacro %}

web/templates/photo.html
{% from 'bootstrap/form.html' import render_form, render_field %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% macro render_photo(photo, current_user) %}
  <div class="card mt-5">
    {% if current_user.username == photo.photoOwner %}
      {% set delete_form = photo.delete_form %}
      <div class="m-2">
        <span class="float-right">
          {{ delete_form.id }}
          {{ delete_form.action }}
          <btn type="button" class="btn btn-outline-danger photo-delete">
            X
          </btn>
        </span>
      </div>
    {% endif %}
    <img class="pl-1 pr-1 photo-post" src="{{ photo.image_link }}" class="m-5" alt="{{ photo.photoOwner }}">

    {% set comments = photo.comments | list %}
    {% set tags = photo.tags | list %}
    <div class="card-body">
      <small>{{ photo.timestamp }}</small>
      <a href="{{ url_for('users.view', username=photo.photoOwner) }}">
        <h4>@{{ photo.photoOwner }}</h4>
      </a>
      <p class="card-text">{{ photo.caption }}</p>
      <p class="card-text">
        {% if tags | length != 0 %}
          <h5>
            Tags:
          </h5>
          {% for tag in tags -%}
            {% if tag.acceptedTag -%}
              <a href="{{ url_for('users.view', username=tag.username) }}">
                {{ tag.username }}
              </a>
            {% endif -%}
          {% endfor -%}
        {% endif %}
      </p>
      {% set like_form = photo.like_form %}
      {% set likes = photo.liked | list %}
      {% if like_form.liked == 0 -%}
        <button type="button" class="btn btn-success like-button">
          {{ like_form.id }}
          <i class="fas fa-thumbs-up"></i>
          <span class="badge badge-light pl-1">{{ likes | length }}</span>
        </button>
      {% else -%}
        <button type="button" class="btn btn-warning like-button">
          {{ like_form.id }}
          <i class="fas fa-thumbs-down"></i>
          <span class="badge badge-light pl-1">{{ likes | length }}</span>
        </button>
      {% endif -%}
      <button data-toggle="collapse" data-target="#photo-comments-{{ photo.photoID }}"
              class="btn btn-primary">
        Comments
        <span class="badge badge-light">{{ comments | length }}</span>
      </button>
    </div>

    <div class="card-footer">
      <div id="photo-comments-{{ photo.photoID }}" class="collapse hide">
        <ul class="list-group">
          {% for comment in comments %}
            <div class="card">
              <a href="{{ url_for('users.view', username=comment.username) }}">
                @{{ comment.username }}
              </a>
              <small>
                {{ comment.timestamp }}
              </small>
              <div class="card-text">
                <big>
                  {{ comment.commentText }}
                </big>
              </div>
            </div>
          {% endfor %}
        </ul>
      </div>
      <br>
      <div class="text-center">
        <a href="#" class="btn btn-primary btn-rounded mb-4" data-toggle="modal"
           data-target="#modalCommentForm">
          Comment
        </a>
      </div>

      <div class="modal fade" id="modalCommentForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h4 class="modal-title w-100 font-weight-bold">Comment</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            {% set comment_form = photo.comment_form %}
            <div class="modal-body mx-3">
              <div class="md-form mb-5">
                {{ comment_form.id }}
                {{ comment_form.action }}
                {{ comment_form.content(class='form-control') }}
              </div>
            </div>

            <div class="modal-footer d-flex justify-content-center">
              <button class="btn btn-default comment-post">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro render_photos(photos, current_user) %}
  {% for photo in photos %}
    <div class="row">
      <div class="col-md-12">
        {{ render_photo(photo, current_user) }}
      </div>
    </div>
  {% endfor %}
{% endmacro %}